#include "model/UiState.h"
#include <algorithm>
#include <atomic>
#include <type_traits>
namespace bw::ui {
namespace {
bool validPeerId(const std::string& value){if(value.empty()||value.size()>64)return false;return std::all_of(value.begin(),value.end(),[](const unsigned char c){return(c>='A'&&c<='Z')||(c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='.'||c=='_'||c==':'||c=='-';});}
std::string jsonString(const std::string& line,const std::string& key){const std::string marker="\""+key+"\":\"";const auto begin=line.find(marker);if(begin==std::string::npos)return{};const auto valueBegin=begin+marker.size();const auto end=line.find('"',valueBegin);if(end==std::string::npos)return{};return line.substr(valueBegin,end-valueBegin);}
std::atomic<std::uint64_t> analysisSequence{0};
}
UiStateStore::UiStateStore():snapshot_(std::make_shared<const UiState>()){}std::shared_ptr<const UiState> UiStateStore::snapshot()const{std::lock_guard lock(mutex_);return snapshot_;}
void UiStateStore::reduce(const UiEvent&e){std::lock_guard lock(mutex_);auto n=std::make_shared<UiState>(*snapshot_);std::visit([&](const auto&v){using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,ConnectionChanged>)n->connection=v.value;else if constexpr(std::is_same_v<T,ScopeChanged>){n->scope=v.value;if(v.value.confirmed){n->link="confirmed";n->confirmationNonce.clear();}}else if constexpr(std::is_same_v<T,LinkConfirmationPending>){n->link="pending";n->confirmationNonce=v.nonce;}else if constexpr(std::is_same_v<T,ForkConfirmationPending>){n->forkConfirmation=v.value;n->fork="confirmation pending";}else if constexpr(std::is_same_v<T,ForkCommitted>){if(n->scope.projectId==v.sourceProjectId)n->scope.projectId=v.newProjectId;n->forkConfirmation.reset();n->fork="committed";}else if constexpr(std::is_same_v<T,ForkFailed>){n->forkConfirmation.reset();n->fork="error: "+v.error;}else if constexpr(std::is_same_v<T,SessionChanged>)n->session=v.value;else if constexpr(std::is_same_v<T,AnalysisChanged>)n->analysis=v.value;else if constexpr(std::is_same_v<T,ProposalChanged>){n->proposal=v.value;n->showProposalDrawer=v.value.has_value();}else if constexpr(std::is_same_v<T,ApprovalChanged>)n->approval=v.value;else if constexpr(std::is_same_v<T,ArmChanged>){n->scheduler=v.value;n->countdownBeats=v.beats;}else if constexpr(std::is_same_v<T,HealthChanged>){n->droppedSnapshots=v.dropped;n->error=v.error;}},e);snapshot_=std::move(n);}
UiAction UiAction::analyze(std::string p,std::string i,std::string c){UiAction a{.kind=Kind::analyze};a.projectId=std::move(p);a.instanceId=std::move(i);a.clipSid=std::move(c);a.token="analysis-"+std::to_string(analysisSequence.fetch_add(1,std::memory_order_relaxed)+1);return a;}UiAction UiAction::stop(){return{.kind=Kind::stop};}UiAction UiAction::linkConfirmRequest(){return{.kind=Kind::linkConfirmRequest};}UiAction UiAction::linkConfirmAccept(std::string x){return{.kind=Kind::linkConfirmAccept,.token=std::move(x)};}UiAction UiAction::focusSet(std::string p,std::string i,std::string c){UiAction a{.kind=Kind::focusSet};a.projectId=std::move(p);a.instanceId=std::move(i);a.clipSid=std::move(c);return a;}UiAction UiAction::forkRequest(std::string s,std::string t){UiAction a{.kind=Kind::forkRequest};a.sourceProjectId=std::move(s);a.newProjectId=std::move(t);return a;}UiAction UiAction::forkConfirm(std::string s,std::string t,std::string k){UiAction a{.kind=Kind::forkConfirm};a.sourceProjectId=std::move(s);a.newProjectId=std::move(t);a.token=std::move(k);return a;}
bool UiActionQueue::enqueue(UiAction a){std::lock_guard lock(mutex_);if(queue_.size()>=kCapacity)return false;queue_.push_back(std::move(a));return true;}bool UiActionQueue::tryPop(UiAction&a){std::lock_guard lock(mutex_);if(queue_.empty())return false;a=std::move(queue_.front());queue_.pop_front();return true;}
bool encodePeerAction(const UiAction&a,std::string&message){switch(a.kind){case UiAction::Kind::analyze:if(validPeerId(a.token)&&validPeerId(a.projectId)&&validPeerId(a.instanceId)&&(a.clipSid.empty()||validPeerId(a.clipSid))){message="{\"type\":\"analysis.request\",\"requestId\":\""+a.token+"\",\"scope\":{\"projectId\":\""+a.projectId+"\",\"instanceId\":\""+a.instanceId+"\"";if(!a.clipSid.empty())message+=",\"clipSid\":\""+a.clipSid+"\"";message+="}}";return true;}return false;case UiAction::Kind::linkConfirmRequest:message="{\"type\":\"link.confirm.request\"}";return true;case UiAction::Kind::linkConfirmAccept:if(validPeerId(a.token)){message="{\"type\":\"link.confirm.accept\",\"nonce\":\""+a.token+"\"}";return true;}return false;case UiAction::Kind::focusSet:if(validPeerId(a.projectId)&&validPeerId(a.instanceId)&&(a.clipSid.empty()||validPeerId(a.clipSid))){message="{\"type\":\"focus.set\",\"scope\":{\"projectId\":\""+a.projectId+"\",\"instanceId\":\""+a.instanceId+"\"";if(!a.clipSid.empty())message+=",\"clipSid\":\""+a.clipSid+"\"";message+="}}";return true;}return false;case UiAction::Kind::forkRequest:if(validPeerId(a.sourceProjectId)&&validPeerId(a.newProjectId)){message="{\"type\":\"session.fork.request\",\"sourceProjectId\":\""+a.sourceProjectId+"\",\"newProjectId\":\""+a.newProjectId+"\"}";return true;}return false;case UiAction::Kind::forkConfirm:if(validPeerId(a.sourceProjectId)&&validPeerId(a.newProjectId)&&validPeerId(a.token)){message="{\"type\":\"session.fork.confirm\",\"sourceProjectId\":\""+a.sourceProjectId+"\",\"newProjectId\":\""+a.newProjectId+"\",\"token\":\""+a.token+"\"}";return true;}return false;case UiAction::Kind::stop:case UiAction::Kind::proposalApprove:case UiAction::Kind::phraseArm:return false;}return false;}
bool reducePeerMessage(UiStateStore&store,const std::string&message){const auto type=jsonString(message,"type");if(type=="link.confirm.pending"||type=="link.status"){auto scope=store.snapshot()->scope;const auto projectId=jsonString(message,"projectId"),instanceId=jsonString(message,"instanceId"),trackSid=jsonString(message,"trackSid"),trackHint=jsonString(message,"trackHint"),clipSid=jsonString(message,"clipSid");if(!projectId.empty())scope.projectId=projectId;if(!instanceId.empty())scope.instanceId=instanceId;scope.trackHint=trackHint.empty()?trackSid:trackHint;scope.clipSid=clipSid.empty()?std::nullopt:std::optional<std::string>(clipSid);scope.confirmed=type=="link.status"&&jsonString(message,"status")=="confirmed";store.reduce(ScopeChanged{std::move(scope)});if(type=="link.confirm.pending")store.reduce(LinkConfirmationPending{jsonString(message,"nonce")});return true;}if(type=="focus.status"){auto scope=store.snapshot()->scope;const auto projectId=jsonString(message,"projectId"),instanceId=jsonString(message,"instanceId"),clipSid=jsonString(message,"clipSid");if(!projectId.empty())scope.projectId=projectId;if(!instanceId.empty())scope.instanceId=instanceId;scope.clipSid=clipSid.empty()?std::nullopt:std::optional<std::string>(clipSid);store.reduce(ScopeChanged{std::move(scope)});return true;}if(type=="session.fork.confirmation_required"){ForkConfirmationView pending{jsonString(message,"token"),jsonString(message,"sourceProjectId"),jsonString(message,"newProjectId")};if(pending.token.empty()||pending.sourceProjectId.empty()||pending.newProjectId.empty())return false;store.reduce(ForkConfirmationPending{std::move(pending)});return true;}if(type=="ProjectForkCommitted"){const auto sourceProjectId=jsonString(message,"sourceProjectId"),newProjectId=jsonString(message,"newProjectId");if(sourceProjectId.empty()||newProjectId.empty())return false;store.reduce(ForkCommitted{sourceProjectId,newProjectId});return true;}if(type=="analysis.status"){store.reduce(SessionChanged{"open"});store.reduce(AnalysisChanged{jsonString(message,"status")});return true;}if(type=="conversation.chunk"){store.reduce(AnalysisChanged{jsonString(message,"text")});return true;}if(type=="analysis.complete"){const auto status=jsonString(message,"status"),error=jsonString(message,"error");store.reduce(AnalysisChanged{status=="error"?"error: "+(error.empty()?"analysis_failed":error):status});return true;}if(type=="action.error"){const auto error=jsonString(message,"error");if(error.rfind("fork_",0)==0)store.reduce(ForkFailed{error});store.reduce(HealthChanged{store.snapshot()->droppedSnapshots,error});store.reduce(AnalysisChanged{"error: "+error});return true;}return false;}
}
